@baseUrl=http://localhost:8002/v2/2024

### User Registration
POST {{baseUrl}}/user/login
Authorization: valid-token
Content-Type: application/json

{
  "email": "penguinnguyen117@gmail.com",
  "purpose": "test"
}