@baseUrl=http://localhost:8004/v1/2024
@baseUrl2=http://localhost:8008/v1/2024
### User registration
POST {{baseUrl}}/user/register
Content-Type: application/json

{
  "email": "penguinnguyen117@gmail.com",
  "purpose": "test"
}

### Test status
GET {{baseUrl}}/ping

### Test docker-compose build
GET {{baseUrl2}}/ping